import Navbar from '@/components/navbar';
import './globals.css';
import { Grid, ThemeProvider, createTheme } from '@mui/material';
import theme from '@/theme';
import Image from 'next/image';
import BackgroundImg from '@/assets/home-background.png';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider theme={theme}>
          <Grid minHeight='100vh' display={'flex'} flexDirection={'column'}>
            <Navbar />
            <Image src={BackgroundImg} alt='' className='home-background' />
            <Grid flexGrow={1} display={'flex'} flexDirection={'column'}>
              {children}
            </Grid>
          </Grid>
        </ThemeProvider>
      </body>
    </html>
  );
}
